server:
  port: 8080
spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true